# Spring Boot Configuration - PRODUCCION/DESARROLLO (MongoDB)

spring.data.mongodb.uri=mongodb://${MONGO_USER:user}:${MONGO_PASSWORD:1234}@localhost:27017/${MONGO_DATABASE:mini-twitter}?authSource=admin

# Logging
logging.level.org.springframework.boot=INFO
